package com.astro.storm.util

import com.astro.storm.data.model.VedicChart
import com.astro.storm.data.model.ZodiacSign

class ChartReportGenerator(private val chart: VedicChart) {

    fun generatePlainTextReport(): String {
        return buildString {
            appendLine("═══════════════════════════════════════════════════════════")
            appendLine("                  VEDIC BIRTH CHART")
            appendLine("═══════════════════════════════════════════════════════════")
            appendLine()

            appendLine("BIRTH INFORMATION")
            appendLine("─────────────────────────────────────────────────────────")
            appendLine("Name          : ${chart.birthData.name}")
            appendLine("Date & Time   : ${chart.birthData.dateTime}")
            appendLine("Location      : ${chart.birthData.location}")
            appendLine("Coordinates   : ${formatCoordinate(chart.birthData.latitude, true)}, ${formatCoordinate(chart.birthData.longitude, false)}")
            appendLine("Timezone      : ${chart.birthData.timezone}")
            appendLine()

            appendLine("ASTRONOMICAL DATA")
            appendLine("─────────────────────────────────────────────────────────")
            appendLine("Julian Day    : ${String.format("%.6f", chart.julianDay)}")
            appendLine("Ayanamsa      : ${chart.ayanamsaName}")
            appendLine("Ayanamsa Value: ${formatDegree(chart.ayanamsa)}")
            appendLine("Ascendant     : ${formatDegree(chart.ascendant)} (${ZodiacSign.fromLongitude(chart.ascendant).displayName})")
            appendLine("Midheaven     : ${formatDegree(chart.midheaven)} (${ZodiacSign.fromLongitude(chart.midheaven).displayName})")
            appendLine("House System  : ${chart.houseSystem.displayName}")
            appendLine()

            appendLine("PLANETARY POSITIONS (Sidereal)")
            appendLine("─────────────────────────────────────────────────────────")
            chart.planetPositions.forEach { position ->
                appendLine(position.toLLMString())
            }
            appendLine()

            appendLine("HOUSE CUSPS")
            appendLine("─────────────────────────────────────────────────────────")
            chart.houseCusps.forEachIndexed { index, cusp ->
                val sign = ZodiacSign.fromLongitude(cusp)
                appendLine("House ${(index + 1).toString().padStart(2)}: ${formatDegree(cusp)} (${sign.displayName})")
            }
            appendLine()

            appendLine("NAKSHATRA DETAILS")
            appendLine("─────────────────────────────────────────────────────────")
            chart.planetPositions.forEach { position ->
                appendLine("${position.planet.displayName.padEnd(10)}: ${position.nakshatra.displayName.padEnd(20)} Pada ${position.nakshatraPada} | Ruler: ${position.nakshatra.ruler.displayName}")
            }
            appendLine()

            appendLine("═══════════════════════════════════════════════════════════")
            appendLine("Generated by AstroStorm - Ultra-Precision Vedic Astrology")
            appendLine("Calculation Engine: Swiss Ephemeris (JPL Mode)")
            appendLine("═══════════════════════════════════════════════════════════")
        }
    }

    private fun formatCoordinate(value: Double, isLatitude: Boolean): String {
        val abs = kotlin.math.abs(value)
        val degrees = abs.toInt()
        val minutes = ((abs - degrees) * 60).toInt()
        val seconds = ((((abs - degrees) * 60) - minutes) * 60).toInt()
        val direction = if (isLatitude) {
            if (value >= 0) "N" else "S"
        } else {
            if (value >= 0) "E" else "W"
        }
        return "$degrees° $minutes' $seconds\" $direction"
    }

    private fun formatDegree(degree: Double): String {
        val normalizedDegree = (degree % 360.0 + 360.0) % 360.0
        val deg = normalizedDegree.toInt()
        val min = ((normalizedDegree - deg) * 60).toInt()
        val sec = ((((normalizedDegree - deg) * 60) - min) * 60).toInt()
        return "$deg° $min' $sec\""
    }
}
